const routes = require('express').Router();
const { registerController, loginController, registerMaster } = require('../controllers/authcontrollers');
const { createSubs, getAllSubs, getSubsById, updateSubs } = require('../controllers/subsControllers');
const notificationController = require('../controllers/Notifications');
routes.post('/subs', createSubs);
routes.get('/subs', getAllSubs);
routes.get('/subs/:id', getSubsById);
routes.put('/subs/:id', updateSubs);
routes.delete('/subs/:id', require('../controllers/subsControllers').deleteSubs);
routes.get('/subs/master/:idMaster', require('../controllers/subsControllers').getSubsByMasterId);
routes.post('/register', registerController);
routes.post('/login', loginController);
routes.post('/register-master', registerMaster);
routes.post('/payment', require('../controllers/paymentController'));
routes.post('/posts', require('../controllers/postsController').createPost);
routes.get('/posts', require('../controllers/postsController').getPosts);
routes.get('/posts/user/:id', require('../controllers/postsController').getPostsByUser);
routes.delete('/posts/:id', require('../controllers/postsController').deletePost);
routes.get('/areas/:city', require('../controllers/postsController').getManagedAreaByCity);
routes.get('/notifications/:id', notificationController.getNotifications);
routes.get('/posts/:id', require('../controllers/postsController').getPostByID);
module.exports = routes;